language: node_js
node_js:
  v12.12.0

cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
